const response = [
  {
    app_id: 'omie',
    name: 'Mock Omie',
    color: '#001E27',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/omie/omie-icon.svg',
    link: 'https://pluga.co/ferramentas/omie/',
  },
  {
    app_id: 'hotmart',
    name: 'Mock Hotmart',
    color: '#F04E23',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/hotmart/hotmart-icon.svg',
    link: 'https://pluga.co/ferramentas/hotmart/',
  },
  {
    app_id: 'eduzz',
    name: 'Mock Eduzz',
    color: '#FFCD33',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/eduzz/eduzz-icon.svg',
    link: 'https://pluga.co/ferramentas/eduzz/',
  },
  {
    app_id: 'jira',
    name: 'Mock Jira Software',
    color: '#0052cc',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/jira/jira-icon.svg',
    link: 'https://pluga.co/ferramentas/jira/',
  },
  {
    app_id: 'superlogica',
    name: 'Mock Superlógica Assinaturas',
    color: '#43AA96',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/superlogica/superlogica-icon.svg',
    link: 'https://pluga.co/ferramentas/superlogica/',
  },
  {
    app_id: 'calendly',
    name: 'Mock Calendly',
    color: '#656a74',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/calendly/calendly-icon.svg',
    link: 'https://pluga.co/ferramentas/calendly/',
  },
  {
    app_id: 'google_docs',
    name: 'Mock Google Docs',
    color: '#005CE2',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/google_docs/google_docs-icon.svg',
    link: 'https://pluga.co/ferramentas/google_docs/',
  },
  {
    app_id: 'twilio',
    name: 'Mock Twilio',
    color: '#cf272c',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/twilio/twilio-icon.svg',
    link: 'https://pluga.co/ferramentas/twilio/',
  },
  {
    app_id: 'eventbrite',
    name: 'Mock Eventbrite',
    color: '#FF8300',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/eventbrite/eventbrite-icon.svg',
    link: 'https://pluga.co/ferramentas/eventbrite/',
  },
  {
    app_id: 'pipefy',
    name: 'Mock Pipefy',
    color: '#3B5BFD',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/pipefy/pipefy-icon.svg',
    link: 'https://pluga.co/ferramentas/pipefy/',
  },
  {
    app_id: 'active_campaign',
    name: 'Mock ActiveCampaign',
    color: '#356ae6',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/active_campaign/active_campaign-icon.svg',
    link: 'https://pluga.co/ferramentas/active_campaign/',
  },
  {
    app_id: 'sympla',
    name: 'Mock Sympla',
    color: '#0098ff',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/sympla/sympla-icon.svg',
    link: 'https://pluga.co/ferramentas/sympla/',
  },
  {
    name: 'Mock Conta Azul',
    app_id: 'conta_azul',
    color: '#2687E9',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/conta_azul/conta_azul-icon.svg',
    link: 'https://pluga.co/ferramentas/conta_azul/',
  },
  {
    name: 'Mock Google Sheets',
    app_id: 'google_sheets',
    color: '#0C7742',
    icon: 'https://s3-sa-east-1.amazonaws.com/pluga.co/apps/icons/google_sheets/google_sheets-icon.svg',
    link: 'https://pluga.co/ferramentas/google_sheets/',
  },
];

module.exports = response;
